apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-score
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credit-score
  template:
    metadata:
      labels:
        app: credit-score
    spec:
      containers:
      - name: credit-score
        image: credit-score:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://finance_user:finance_pass@postgres:5432/finance_db"
        - name: CELERY_BROKER_URL
          value: "amqp://guest:guest@rabbitmq:5672//"
