apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan-service
  template:
    metadata:
      labels:
        app: loan-service
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox
        command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting; sleep 2; done;']
      containers:
      - name: loan-service
        image: loan-service:1.0
        ports:
          - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: loan-service
spec:
  selector:
    app: loan-service
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30667
  type: NodePort
