apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-worker-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: credit-worker
  template:
    metadata:
      labels:
        app: credit-worker
    spec:
      containers:
      - name: credit-worker
        image: credit-worker:latest
        imagePullPolicy: Never
        args: ["celery", "-A", "app.tasks", "worker", "-Q", "credit_queue", "--loglevel=info"]
        env:
        - name: CELERY_BROKER_URL
          value: "amqp://guest:guest@rabbitmq-service:5672//"
        - name: DATABASE_URL
          value: "postgresql://user:password@postgres-service:5432/loan_db"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: property-worker-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: property-worker
  template:
    metadata:
      labels:
        app: property-worker
    spec:
      containers:
      - name: property-worker
        image: property-worker:latest
        imagePullPolicy: Never
        args: ["celery", "-A", "app.tasks", "worker", "-Q", "property_queue", "--loglevel=info"]
        env:
        - name: CELERY_BROKER_URL
          value: "amqp://guest:guest@rabbitmq-service:5672//"
        - name: DATABASE_URL
          value: "postgresql://user:password@postgres-service:5432/loan_db"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-worker
  template:
    metadata:
      labels:
        app: notification-worker
    spec:
      containers:
      - name: notification-worker
        image: notification-worker:latest
        imagePullPolicy: Never
        args: ["celery", "-A", "app.tasks", "worker", "-Q", "notification_queue", "--loglevel=info"]
        env:
        - name: CELERY_BROKER_URL
          value: "amqp://guest:guest@rabbitmq-service:5672//"
        - name: DATABASE_URL
          value: "postgresql://user:password@postgres-service:5432/loan_db"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: decision-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: decision-worker
  template:
    metadata:
      labels:
        app: decision-worker
    spec:
      containers:
      - name: decision-worker
        image: decision-worker:latest
        imagePullPolicy: Never
        args: ["celery", "-A", "app.tasks", "worker", "-Q", "decision_queue", "--loglevel=info"]
        env:
        - name: CELERY_BROKER_URL
          value: "amqp://guest:guest@rabbitmq-service:5672//"
        - name: DATABASE_URL
          value: "postgresql://user:password@postgres-service:5432/loan_db"